/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.function.Executable;


class SumCalculatorTest {
    @BeforeEach
    void sumCalculatorObject(){
        SumCalculator sumCalculator = new SumCalculator();
    }

    @Test
    void sumCalculatorWorksOKFor3(){
        assertEquals(6, new SumCalculator().sum(3));
    }

    @Test
    void sumCalculatorWorksOKFor1(){
        assertEquals(1, new SumCalculator().sum(1));
    }

    @Test
    void sumCalculatorThrowsIllegalArgumentException(){

        assertThrows(IllegalArgumentException.class, new Executable(){
            @Override
            public void execute() throws Throwable {
                new SumCalculator().sum(0 );
            }
        });
    }
}
